language: node_js
node_js:
  - 13

services:
  - docker

install:
  - echo "nothing needs to be installed"


before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t simple-reverse-proxy .
  - docker tag simple-reverse-proxy edx04/simple-reverse-proxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push DOCKER_HUB_ACCOUNT/simple-reverse-proxy

